# -*- coding: utf-8 -*-

# Define here the models for your scraped items
#
# See documentation in:
# https://doc.scrapy.org/en/latest/topics/items.html

import scrapy


class Item(scrapy.Item):
    isActive = scrapy.Field()
    startDate = scrapy.Field()
    id = scrapy.Field()
    ppFacebook = scrapy.Field()
    ppInstagram = scrapy.Field()
    ppAudienceNetwork = scrapy.Field()
    ppMessenger = scrapy.Field()
    page_name = scrapy.Field()
    page_id = scrapy.Field()
    page_profile_picture_url = scrapy.Field()
    page_profile_uri = scrapy.Field()
    page_categories = scrapy.Field()
    sponsored = scrapy.Field()
    body_text = scrapy.Field()
    body_html = scrapy.Field()
    image_url1 = scrapy.Field()
    image_url2 = scrapy.Field()
    image_url3 = scrapy.Field()
    image_url4 = scrapy.Field()
    image_url5 = scrapy.Field()
    image_url6 = scrapy.Field()
    image_url7 = scrapy.Field()
    image_url8 = scrapy.Field()
    image_url9 = scrapy.Field()
    image_url10 = scrapy.Field()
    image_url11 = scrapy.Field()
    image_url12 = scrapy.Field()
    image_url13 = scrapy.Field()
    image_url14 = scrapy.Field()
    image_url15 = scrapy.Field()
    image_url16 = scrapy.Field()
    image_url17 = scrapy.Field()
    image_url18 = scrapy.Field()
    image_url19 = scrapy.Field()
    image_url20 = scrapy.Field()
    video_url1 = scrapy.Field()
    video_url2 = scrapy.Field()
    video_url3 = scrapy.Field()
    video_url4 = scrapy.Field()
    video_url5 = scrapy.Field()
    video_url6 = scrapy.Field()
    video_url7 = scrapy.Field()
    video_url8 = scrapy.Field()
    video_url9 = scrapy.Field()
    video_url10 = scrapy.Field()
    video_url11 = scrapy.Field()
    video_url12 = scrapy.Field()
    video_url13 = scrapy.Field()
    video_url14 = scrapy.Field()
    video_url15 = scrapy.Field()
    learn_more_link = scrapy.Field()
    display_format = scrapy.Field()
    name = scrapy.Field()
